In [1]:
# 必要なライブラリをインポート
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

# データの読み込み
train = pd.read_csv("./original/train.csv")
test = pd.read_csv("./original/test.csv")

# 特徴量と目的変数に分ける
X_train = train.drop("price_range", axis=1)
y_train = train["price_range"]
X_test = test.copy()

# 特徴量のスケーリング
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# サポートベクターマシンの作成と学習
model = SVC(kernel="linear", random_state=1)
model.fit(X_train, y_train)

# 評価用データの価格帯の予測
y_pred = model.predict(X_test)

# 予測結果の出力
output = pd.DataFrame({"index": test["id"], "price_range": y_pred})
output.to_csv("./submission/submission_svm_v1.csv", index=False, header=False)

In [2]:
output

     index  price_range
0        1            3
1        2            0
2        6            0
3       10            1
4       12            1
..     ...          ...
795   1978            3
796   1980            1
797   1982            1
798   1988            2
799   1998            2

[800 rows x 2 columns]